load("//path/to:rules.bzl", "one_rule")
load("//path/to:more_rules", "bar", "baz")
load("@repo//my/rules:foo.bzl", "bar_library", "baz_library")
load("@repo//somewhere:stuff", foo_lib = "foo", "normal", renamed="_rename_me")
load("//initial:rules",
	"initial_line")
load(
  "@repo//everything/on/its/own:line.bzl",
  "apple",
  cavendish = "banana",
  "cherry",

  "durian"
)
